"""add_file_hash_index

Revision ID: 38e6e3806c35
Revises: ddb3f5e964cf
Create Date: 2026-04-13 12:42:04.342062

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38e6e3806c35"
down_revision: Union[str, Sequence[str], None] = "ddb3f5e964cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_documents_file_hash"), "documents", ["file_hash"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_file_hash"), table_name="documents")
    # ### end Alembic commands ###
